export const GET_MAILS_REQUEST="GET_MAILS_REQUEST";
export const GET_MAILS_SUCCESS="GET_MAILS_SUCCESS";
export const GET_MAILS_ERROR="GET_MAILS_ERROR";
export const CHANGE_POSTMAN="CHANGE_POSTMAN";
export const SUBMIT_ASSIGNMENTS_REQUEST="SUBMIT_ASSIGNMENTS_REQUEST";
export const SUBMIT_ASSIGNMENTS_SUCCESS="SUBMIT_ASSIGNMENTS_SUCCESS";
export const SUBMIT_ASSIGNMENTS_ERROR="SUBMIT_ASSIGNMENTS_ERROR";