export const COMPLAINS_DATA_REQUEST = "COMPLAINS_DATA_REQUEST";
export const COMPLAINS_DATA_SUCCESS = "COMPLAINS_DATA_SUCCESS";
export const COMPLAINS_DATA_ERROR = "COMPLAINS_DATA_ERROR";

export const MARK_SOLVED_REQUEST = "MARK_SOLVED_REQUEST";
export const MARK_SOLVED_SUCCESS = "MARK_SOLVED_SUCCESS";
export const MARK_SOLVED_ERROR = "MARK_SOLVED_ERROR";