export const ADD_POST_START = "ADD_POST_START";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAIL = "ADD_POST_FAIL";

export const GET_POSTOFFICE_START="GET_POSTOFFICE_START";
export const GET_POSTOFFICE_SUCCESS="GET_POSTOFFICE_SUCCESS";
export const GET_POSTOFFICE_FAIL="GET_POSTOFFICE_FAIL";