export const ADD_POST_START = "ADD_POST_START";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAIL = "ADD_POST_FAIL";

export const ADD_REG_POST_START = "ADD_REG_POST_START";
export const ADD_REG_POST_SUCCESS = "ADD_REG_POST_SUCCESS";
export const ADD_REG_POST_FAIL = "ADD_REG_POST_FAIL";

export const ADD_LOGI_POST_START = "ADD_LOGI_POST_START";
export const ADD_LOGI_POST_SUCCESS = "ADD_LOGI_POST_SUCCESS";
export const ADD_LOGI_POST_FAIL = "ADD_LOGI_POST_FAIL";

export const ADD_MONEYORDER_START = "ADD_MONEYORDER_START";
export const ADD_MONEYORDER_SUCCESS = "ADD_MONEYORDER_SUCCESS";
export const ADD_MONEYORDER_FAIL = "ADD_MONEYORDER_FAIL";

export const GET_POSTOFFICE_START="GET_POSTOFFICE_START";
export const GET_POSTOFFICE_SUCCESS="GET_POSTOFFICE_SUCCESS";
export const GET_POSTOFFICE_FAIL="GET_POSTOFFICE_FAIL";

export const GET_MONEYORDERS_START="GET_MONEYORDERS_START";
export const GET_MONEYORDERS_SUCCESS="GET_MONEYORDERS_SUCCESS";
export const GET_MONEYORDERS_FAIL="GET_MONEYORDERS_FAIL";