export const GET_TRANSFERS_REQUEST="GET_TRANSFERS_REQUEST";
export const GET_TRANSFERS_SUCCESS="GET_TRANSFERS_SUCCESS";
export const GET_TRANSFERS_ERROR="GET_TRANSFERS_ERROR";

export const CONFIRM_TRANSFER_REQUEST="CONFIRM_TRANSFER_REQUEST";
export const CONFIRM_TRANSFER_SUCCESS="CONFIRM_TRANSFER_SUCCESS";
export const CONFIRM_TRANSFER_ERROR="CONFIRM_TRANSFER_ERROR";