export const POSTMEN_ROUTES_DATA_REQUEST = " POSTMEN_ROUTES_DATA_REQUEST";
export const  POSTMEN_ROUTES_DATA_SUCCESS = " POSTMEN_ROUTES_DATA_SUCCESS";
export const  POSTMEN_ROUTES_DATA_ERROR = " POSTMEN_ROUTES_DATA_ERROR";

export const  POSTMAN_ROUTE_SAVE_REQUEST = "POSTMAN_ROUTE_SAVE_REQUEST";
export const POSTMAN_ROUTE_SAVE_SUCCESS = "POSTMAN_ROUTE_SAVE_SUCCESS";
export const POSTMAN_ROUTE_SAVE_ERROR = "POSTMAN_ROUTE_SAVE_ERROR";

export const  POSTMAN_ROUTE_REMOVE_REQUEST = "POSTMAN_ROUTE_REMOVE_REQUEST";
export const POSTMAN_ROUTE_REMOVE_SUCCESS = "POSTMAN_ROUTE_REMOVE_SUCCESS";
export const POSTMAN_ROUTE_REMOVE_ERROR = "POSTMAN_ROUTE_REMOVE_ERROR";